fix(wizard): fixes multilingual/multispeaker config setting in new projects
EveryVoiceTTS/EveryVoice pull request #510
Opened 2024-07-16 15:32 UTC by wiitt

### PR Goal? 
This PR fixes multilingual/multispeaker config setting for new projects.

### Fixes? 
Fixes 470 (https://github.com/EveryVoiceTTS/EveryVoice/issues/470).

### Feedback sought? 

1. Check the correctness of the commit history. The branch for this PR has been rebased on top of the PR https://github.com/EveryVoiceTTS/EveryVoice/pull/509 branch.
2. Feedback on wording of new prompts in the wizard is greatly appreciated.
3. Take a close look at test_wizard.py/WizardTest/test_running_out_of_columns. It has steps added to make the test case complete.  I though that it would be better if the test would go through all steps and compare output with the expected one. Is it appropriate for this test or was it testing some other aspect rather work of the tour?

### Priority? 
Medium.

### Tests added? 
Modified the complete-tour wizard tests to match new wizard workflow. Added a new complete-tour wizard test with two datasets to check correctness of multilingual/multispeaker marking.

### How to test? 
Run the wizard and create projects with various combinations of datasets (same language/same speaker; same language/different speakers; different languages/same speaker; different language/different speakers; with a specified language/speaker column). Try out different answers to two new questions.

### Confidence? 
Medium. Big update.

### Version change? 
Can be included in a new release with more important fixes.  

### Related PRs? 
PR https://github.com/EveryVoiceTTS/EveryVoice/pull/509 should be merged first.

2024-07-16 16:36 UTC, wiitt commented
Made the last forced push to cover with testing two additional lines.

2024-07-17 16:46 UTC, wiitt commented
@roedoejet I've changed the branch to merge into to the branch from https://github.com/EveryVoiceTTS/EveryVoice/pull/509.

2024-07-17 20:02 UTC, roedoejet requested changes
I think we should refer to it as a speaker ID instead of name, but this looks great so far, with extensive testing. I will test it out on my machine now but just wanted to post some of these text requested changes in the meantime. Thanks @wiitt !

2024-07-17 20:02 UTC, roedoejet commented on everyvoice/wizard/dataset.py
> +            "Note: if your dataset has speakers with names matching with speakers from other provided datasets, they will be considered the same. If it is not a desired behaviour, you will have to al
```suggestion
            "Note: if your dataset has speakers with names matching with speakers from other provided datasets, they will be considered the same. If this is not the desired behaviour, you will have to alter the speaker names in the relevant datasets to indicate that they are different."
```

2024-07-17 20:02 UTC, roedoejet commented on everyvoice/wizard/dataset.py
> +            title="Would you like to specify the speaker name? Otherwise a default name with the dataset id will be assigned.",
```suggestion
            title=f"Would you like to specify a speaker ID for this dataset? Otherwise a default ID of 'speaker_{dataset_index}' will be assigned.",
```

and you could define `dataset_index = self.state_subset.split("_")[-1]` in the prompt

2024-07-17 20:02 UTC, roedoejet commented on everyvoice/wizard/dataset.py
> +                f"OK, '{self.state[StepNames.add_speaker_step]}' will be used as a speaker name in this dataset then."
```suggestion
                f"OK, '{self.state[StepNames.add_speaker_step]}' will be used as a speaker ID in this dataset then."
```

2024-07-17 20:02 UTC, roedoejet commented on everyvoice/wizard/dataset.py
> +        return input("Please enter the speaker name: ")
```suggestion
        return input("Please enter the desired speaker ID: ")
```

2024-07-17 20:02 UTC, roedoejet commented on everyvoice/wizard/dataset.py
> +            print("Sorry, the speaker needs a name.")
```suggestion
            print("Sorry, the speaker needs an ID.")
```

2024-07-17 20:02 UTC, roedoejet commented on everyvoice/wizard/dataset.py
> +                f"Sorry, your name: '{response}' is not valid. Please avoid using special characters in it and re-type something like {slug} instead."
```suggestion
                f"Sorry, your ID: '{response}' is not valid. Please avoid using special characters in it and re-type something like {slug} instead."
```

2024-07-17 20:02 UTC, roedoejet commented on everyvoice/wizard/dataset.py
> +            f"Great! '{self.response}' will be used as a speaker name in this dataset."
```suggestion
            f"Great! '{self.response}' will be used as the speaker ID for this dataset."
```

2024-07-17 21:40 UTC, wiitt commented on everyvoice/wizard/dataset.py
> +            "Note: if your dataset has speakers with names matching with speakers from other provided datasets, they will be considered the same. If it is not a desired behaviour, you will have to al
Do we keep "speaker names" here?

2024-07-17 22:13 UTC, roedoejet commented on everyvoice/wizard/dataset.py
> +            "Note: if your dataset has speakers with names matching with speakers from other provided datasets, they will be considered the same. If it is not a desired behaviour, you will have to al
oh no, sorry I missed this. please change all instances of speaker names to speaker IDs

2024-07-18 21:00 UTC, roedoejet approved these changes
lgtm!

2024-07-18 21:16 UTC, merged